In [1]:
import numpy as np
import pandas as pd

In [3]:
df =pd.read_csv("IMDB DataSet.csv")

In [4]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'] =df['review'].str.lower()

In [6]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Remove html tag

In [7]:
import re
def remove_html_tags(text):
    pattern =re.compile('<.*?>')
    return pattern.sub(r'', text)

In [8]:
text = "<html><body><p> Movie <p><p> click here to <a herf ='http://google.com'>download</a>"

In [9]:
remove_html_tags(text)

' Movie  click here to download'

In [10]:
df['review'] =df['review'].apply(remove_html_tags)

In [11]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [30]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [31]:
text2= 'For notebook click https:/www.asd.com/delta/notebookacc'

In [32]:
remove_url(text2)

'For notebook click https:/'

# remove punctuation

In [25]:
import string
import time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [26]:
exclude =string.punctuation

In [27]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [28]:
text1= 'string with . punctuation?,'

In [29]:
remove_punc(text1)

'string with  punctuation'

# spelling correction

In [33]:
pip install TextBlob

   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   --------------------------------------- 624.3/624.3 kB 11.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [34]:
from textblob import TextBlob

In [38]:
incorrect_text= 'certaain conditinas several gernerations are modifieed in the saame maner'

textblob =TextBlob(incorrect_text)
textblob.correct().string

'certain conditions several generations are modified in the same manner'

# remove stepwords

In [40]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [41]:
STOPWORDS =set(stopwords.words('english'))

In [42]:
STOPWORDS

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [45]:
def remove_stopwords(text):
    new_text =[]
    for word in text.split():
        if word in text.split():
            if word in set(stopwords.words('english')):
                new_text.append('')
            else:
                new_text.append(word)

    x= new_text[:]
    new_text.clear()
    return "".join(x)

remove_stopwords('probally my all time fav movie , a story of selflessness , sacrifice and dedication to a nobal cause.')

'proballytimefavmovie,storyselflessness,sacrificededicationnobalcause.'

In [46]:
# word tokenization

In [47]:
sen="I am going to delhi"
sen.split()

['I', 'am', 'going', 'to', 'delhi']

In [49]:
# sentence tokenization
sen2= "i am going to delhi. I will stay there for 3 days . let\'s hpoe the trip to be great"
sen2.split()

['i',
 'am',
 'going',
 'to',
 'delhi.',
 'I',
 'will',
 'stay',
 'there',
 'for',
 '3',
 'days',
 '.',
 "let's",
 'hpoe',
 'the',
 'trip',
 'to',
 'be',
 'great']

In [50]:
# Problem with split func
sen3 ="I am going to delhi!"
sen3.split()

['I', 'am', 'going', 'to', 'delhi!']

# nltk

In [51]:
from nltk.tokenize import word_tokenize , sent_tokenize

In [52]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [53]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [54]:
sent1 ="I am going to delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'delhi', '!']

# Text representation

In [56]:
df = pd.DataFrame({'text':['people watch cricket' , 'player was player' , 'people write comment' ,
                           'cricket play comment' ] , 'output':[1,1,0,0]})

In [57]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [59]:
from sklearn.feature_extraction.text import CountVectorizer

In [60]:
cv = CountVectorizer()

In [63]:
bow =cv.fit_transform(df['text'])

In [64]:
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [65]:

print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [66]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

# 2 N-grams

In [67]:
cv =CountVectorizer(ngram_range=(2,2))

In [68]:
v=CountVectorizer(ngram_range=(1,2))


In [69]:
bow =v.fit_transform(df['text'])

In [70]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [71]:
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [72]:
# TF( tern frequency)
# 2 . IDF (inverse Document frequency)

In [74]:
# TF (t,d) = (number of occurance of term t in document d) / (total number of terms in the document d)

# example ==> 
# d1 = people watch cricket.

# tf(people,d1) =1/3

# d2= match was match .
# tf(match,d2) = 2/3

In [75]:
# IDF (t) == loge(Total numnber of documents in the corpus) / (number of document with term t in them)
# here corpus means number of sentence

# ex ==>
# d1 = people watch cricket.
# d2 = cricket was cricket.
# d3 = people write comment .
# d4 = cricket write comment .



In [76]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [78]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']
